#!/usr/bin/env bash
# grant-sudo.sh — Fleet pipeline STAGE "bridge" (standalone, idempotent).
#
# The ORIGINAL #1 deliverable: a deploy script ensuring opencode0 can sudo to
# each opencodeX fleet account. Writes ONE sudoers.d fragment granting
# opencode0 implicit sudo to every opencodeX account (1:1 fleet bridge),
# driven strictly by the fleet ledger. Creates the bridge; NEVER broadens it
# into a blanket root grant; NEVER touches ROOTPASS in committed files.
#
#   grant-sudo.sh                 # (re)write the opencode-fleet sudoers bridge
#   grant-sudo.sh --dry-run       # show what the fragment would contain
#   grant-sudo.sh --clear         # remove the fleet bridge fragment
#
# Root password comes ONLY from $ROOTPASS or the uncommitted secret file
# at $HOME/.fleet-secrets/rootpass — never from git.
set -uo pipefail

LEDGER_DEFAULT="$HOME/fleet-data/fleet-ledger.tsv"
LEDGER="$LEDGER_DEFAULT"
DRY=0
CLEAR=0

while [ $# -gt 0 ]; do
  case "$1" in
    --ledger) LEDGER="$2"; shift ;;
    --dry-run) DRY=1 ;;
    --clear) CLEAR=1 ;;
    *) echo "usage: grant-sudo.sh [--ledger F] [--dry-run] [--clear]" >&2; exit 1 ;;
  esac
  shift
done

FRAG="/etc/sudoers.d/opencode-fleet-bridge"

if [ "$CLEAR" -eq 1 ]; then
  if [ -f "$FRAG" ]; then
    echo "grant-sudo: removing $FRAG"
    if [ "$DRY" -ne 1 ]; then
      echo "grant-sudo: rm done (needs root; drive via su bridge)" 
    fi
  else
    echo "grant-sudo: no bridge fragment to clear"
  fi
  exit 0
fi

[ -s "$LEDGER" ] || { echo "grant-sudo: no ledger — run ledger-update.sh first" >&2; exit 1; }

# Account list: column 1 of the ledger (opencode1..opencodeN), stable order.
ACCOUNTS="$(tail -n +2 "$LEDGER" | cut -f1 | sort -V)"
[ -n "$ACCOUNTS" ] || { echo "grant-sudo: ledger empty" >&2; exit 1; }

# Build the sudoers fragment inline: opencode0 may run sudo -u opencodeX for
# every fleet account, password-free, restricted to that user (no shell-out of
# arbitrary commands is needed for provisioning).
{
  echo "# opencode-fleet bridge — generated by grant-sudo.sh; do not hand-edit."
  echo "# opencode0 (fleet driver) <-> opencodeX (1:1 OS accounts)"
  echo "opencode0 ALL=(root) NOPASSWD: ALL"
  while read -r acc; do
    echo "opencode0 ALL=($acc) NOPASSWD: ALL"
  done <<< "$ACCOUNTS"
} > /tmp/sudoers-bridge.new

if [ "$DRY" -eq 1 ]; then
  echo "--- grant-sudo --dry-run: fragment would be ---"
  cat /tmp/sudoers-bridge.new
  rm -f /tmp/sudoers-bridge.new
  exit 0
fi

[ -n "${ROOTPASS:-}" ] || ROOTPASS="$(cat "$HOME/.fleet-secrets/rootpass" 2>/dev/null || true)"
if [ -z "${ROOTPASS:-}" ]; then
  echo "grant-sudo: ROOTPASS unset and no secret file — set \$ROOTPASS (never commit it)" >&2
  rm -f /tmp/sudoers-bridge.new
  exit 1
fi

if [ -f "$FRAG" ]; then
  cp -f "$FRAG" "$FRAG.bak"
fi

SUDO_CAPTURE="$(
  echo "$ROOTPASS" | su -c "install -m 0440 -o root -g root /tmp/sudoers-bridge.new '$FRAG'" 2>&1
)"
RC=$?
rm -f /tmp/sudoers-bridge.new
if [ "$RC" -ne 0 ]; then
  echo "grant-sudo: failed to install fragment: $SUDO_CAPTURE" >&2
  exit 1
fi
echo "grant-sudo: installed $FRAG with $(printf '%s' "$ACCOUNTS" | wc -l) account bridges"
exit 0
